require:
  - rubocop
  - rubocop-rails

AllCops:
  EnabledByDefault: true

Style/Copyright:
  # Description: 'Include a copyright notice in each file before any code.'
  Enabled: false
  # VersionAdded: '0.30'
  # Notice: '^Copyright (\(c\) )?2[0-9]{3} .+'
  # AutocorrectNotice: ''