default: &default
  adapter: postgresql
  encoding: unicode
  template: template0
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432
  username: moiz
  password: 


development:
  <<: *default
  database: pathsync_development

test:
  <<: *default
  database: pathsync_test
  host: localhost
  username: postgres
  password: postgres

production:
  <<: *default
  database: pathsync_production
  username: pathsync
  password: <%= ENV['FREELANCE_DATABASE_PASSWORD'] %>